server:
  port: 7000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2b8
    username: root
    password: 333
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: SCW-USER
  redis:
    password: 123456
    host: 192.168.188.129
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    path: E:\document\java\javaEE\log
  level:
    com:
      yb: debug

sms:
  host: http://dingxin.market.alicloudapi.com
  path: /dx/sendSms
  method: POST
  appCode: APPCODE 64cc981872674ff486500856548f76c5

#mybatis:
#  mapper-locations: classpath:com/yb/user/mapper
#  config-location: classpath:mybatis/mybatis-config.xml