server:
  port: 9000

spring:
  datasource:
    username: root
    password: 333
    url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    port: 6379
    password: 123456
    host: 192.168.188.129

  application:
    name: SCW-ORDER

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
