server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2b8
    username: root
    password: 333
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: SCW-PROJECT
  redis:
    password: 123456
    host: 192.168.188.129
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    path: E:\document\java\javaEE\log
  level:
    com:
      yb: debug

oss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4GH8W73RvDK3JbMwr5i1
  accessKeySecret: Ba1W9ofraOgHxu4eb1ZrZf76JNTFO8
  bucketName: 20201210-day
  bucketDomain: https://20201210-day.oss-cn-beijing.aliyuncs.com

#mybatis:
#  mapper-locations: classpath:com/yb/project/mapper
#  config-location: classpath:mybatis/mybatis-config.xml